[package]
name = "sockrs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.2.7", features = ["cargo", "derive"] }
json = "0.12.4"
serde_json = "1.0.96"
tokio = "1.28.0"


